### ISSUE TITLE
All lights flash when notes are played

### ISSUE THREAD

**Issue by roim** [ojacques/SynthesiaKontrol#10] opened 2019-08-11 01:12 UTC
Just followed installation steps with an 88MK2 and this happens. If I enable Synthesia's metronome this happens more often, so I'm wondering if it's listening to MIDI input it didn't intend to?

https://imgur.com/a/lExyds4

Logs don't show any lead:
![log](https://user-images.githubusercontent.com/1657711/62828392-20227e80-bb9a-11e9-84cc-adb66503c9d1.png)

I might take a look at this soon

**Comment by ojacques** [comment] 2019-10-01 11:58
Hmm. Very interesting. Logs look OK. I wonder if you have another program opened, maybe Komplete Kontrol, which would like to take over the lights on the keyboard?

**Comment by ojacques** [comment] 2020-02-12 22:04
Closing, can't reproduce this. I suspect another program (Komplete Kontrol) is conflicting. Make sure it is closed when running this little app...

**Closed by ojacques** 2020-02-12 22:04 UTC
